# -*- coding: utf-8 -*-
"""PDTD [Modul 3].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11BPE3xNxIgcI3wQa8qLO-GZCvxz3SZnf

# **Pelatihan Dasar Teknologi Digital Modul 3**
Pernyataan Kondisional

if, elif, else

kondisional bersarang

logika kondisional

**1. If, else**
"""

#pernyataan kondisional sederhana (2 kondisi)
cuaca = input("Apakah sedang hujan? (ya/tidak): ").lower()
if cuaca == "ya":
    print("Pakai payung!")
else:
    print("Tidak perlu pakai payung!")

"""**2. if, elif, else**"""

#pernyataan kondisional dengan 3 kondisi
angka = int(input("Masukkan sebuah angka: "))  #inputan
if angka > 0:
    print("Angka tersebut positif.")
elif angka < 0:
    print("Angka tersebut negatif.")
else:
    print("Angka tersebut nol.")

"""if statement: Menjalankan blok kode jika kondisi benar.

elif statement: Memeriksa kondisi tambahan jika kondisi sebelumnya salah.

else statement: Menjalankan blok kode jika semua kondisi sebelumnya salah.

**3. Kondisional Bersarang**
"""

umur = int(input("Umur kamu berapa nih? "))

if umur >= 18:
    if umur >= 60:
        print("Wow! Sudah level legenda nih! 🧓😎")
    else:
        print("Dewasa ya... tapi jangan lupa bayar tagihan listrik 😜")
else:
    print("Masih bocil ya? Nikmatin dulu masa main layangannya! 🪁")

"""**4. Operator logika**

and: Mengembalikan True jika kedua kondisi benar.

or: Mengembalikan True jika setidaknya satu kondisi benar.

not: Membalik nilai kebenaran dari kondisi.
"""

print("🌤️ === Cek Suhu Harian Kamu === 🌡️")

# Input: suhu
suhu = int(input("Masukkan suhu sekarang (°C): "))

# Cek kondisi suhu
if suhu > 20 and suhu < 30:
    print("Pas banget! Cuacanya hangat, enak buat nongkrong di luar ☕😎")
elif suhu <= 20:
    print("Brrr... dingin banget! Saatnya selimutan dan nonton drakor 🧣❄️")
else:
    print("Panas banget woy! Jangan lupa minum air biar nggak meleleh 🔥🥵")

print("🎟️ === Cek Diskon Tiket Spesial === 🎟️")

usia = int(input("Berapa usia kamu sekarang? "))
pelajar = input("Apakah kamu masih pelajar? (ya/tidak): ").lower()

# Cek apakah memenuhi syarat untuk diskon
if (usia >= 18 and usia <= 25) or pelajar == "ya":
    print("🎉 Selamat! Kamu berhak dapet tiket harga diskon! 💸")
    print("Manfaatkan selagi muda — nanti umur nambah, diskon hilang 😜")
else:
    print("😅 Maaf, belum ada diskon buat kamu.")
    print("Tapi tenang, semangatmu tetap tak ternilai! 💪")

"""# LATIHAN

***Latihan 1***
"""

print("🔒 === Sistem Autentikasi PIN === 🔑")

# PIN yang sudah ditentukan
pin_benar = 1234

# Input dari pengguna
pin_dimasukkan = int(input("Masukkan PIN kamu: "))

# Memeriksa apakah PIN yang dimasukkan benar
if pin_dimasukkan == pin_benar:
    print("✅ Autentikasi berhasil! Selamat datang, agen rahasia 😎")
else:
    print("❌ PIN salah. Akses ditolak! Jangan sampai salah lagi, ya 😅")

"""***Latihan 2***"""

print("📖 === Perpustakaan Santai === 📖")

# Inisialisasi variabel
stok_buku = 5

# Input jumlah peminjam
jumlah_peminjaman = int(input("Masukkan jumlah buku yang ingin dipinjam: "))

# Cek apakah peminjaman buku dapat dilakukan
if jumlah_peminjaman <= stok_buku:
    print("🎉 Peminjaman berhasil! Buku siap menemanimu membaca 📚✨")
    stok_buku -= jumlah_peminjaman
    print("Sisa stok buku sekarang:", stok_buku)
else:
    print("😅 Peminjaman gagal. Stok nggak cukup nih!")
    print("Stok tersedia cuma:", stok_buku)

"""***Latihan 3***"""

print("🎟️ === Tiket Seru Bersama Teman === 🎉")

# Inisialisasi variabel
harga_tiket = 150000
jumlah_penumpang = int(input("Masukkan jumlah penumpang: "))
total_harga = harga_tiket * jumlah_penumpang

# Diskon untuk jumlah penumpang lebih dari 4
if jumlah_penumpang > 4:
    diskon = 0.1  # 10%
    total_harga_diskon = total_harga * (1 - diskon)
    print(f"Yeay! Kamu dan teman-teman mendapatkan diskon 10%! 🎊")
    print(f"Total Harga Setelah Diskon: Rp {total_harga_diskon}")
else:
    print("Hmm, belum cukup rame untuk diskon 😅")
    print(f"Total Harga: Rp {total_harga}")

print("Selamat menikmati perjalanan! ✈️🍿")

"""***Latihan 4***"""

# Inisialisasi variabel
sisa_anggaran = int(input("Berapa sisa anggaran kamu? Rp "))

# Cek status anggaran
if sisa_anggaran > 0:
    print("Mantap! Masih ada sisa Rp", sisa_anggaran, "💸 Mau traktir teman nggak?")
elif sisa_anggaran == 0:
    print("Pas banget! Anggaran kamu kayak perhitungan ninja 💰👌")
else:
    print("Waduh! Anggaran jebol 😱 Kamu minus Rp", abs(sisa_anggaran), "— saatnya hidup hemat dulu nih!")

"""**Special Case**"""

print("=== CEK TINGKAT STRES SEDERHANA ===")

# Pertanyaan 1
p1 = input("1. Apakah kamu sering merasa cemas tanpa alasan jelas? (ya/tidak): ")

# Pertanyaan 2
p2 = input("2. Apakah kamu sulit tidur akhir-akhir ini? (ya/tidak): ")

# Pertanyaan 3
p3 = input("3. Apakah kamu merasa mudah marah atau tersinggung? (ya/tidak): ")

# Pertanyaan 4
p4 = input("4. Apakah kamu merasa lelah secara emosional? (ya/tidak): ")

# Hitung jumlah 'ya'
skor = 0
if p1.lower() == "ya":
    skor += 1

if p2.lower() == "ya":
    skor += 1

if p3.lower() == "ya":
    skor += 1

if p4.lower() == "ya":
    skor += 1

print("\n=== HASIL ===")

# Penilaian berdasarkan skor
if skor == 0:
    print("Kamu tampak sangat tenang. Terus jaga keseimbangan hidupmu!")
elif skor == 1:
    print("Ada sedikit tanda stres, tapi masih ringan. Tetap perhatikan keseharianmu ya.")
elif skor == 2:
    print("Kamu mungkin mengalami stres tingkat sedang. Cobalah istirahat lebih banyak.")
elif skor == 3:
    print("Tanda stresmu cukup jelas. Cobalah berbicara dengan seseorang atau lakukan kegiatan relaksasi.")
else:  # skor == 4
    print("Kamu tampak sangat stres. Jangan ragu mencari dukungan atau bercerita pada orang terpercaya.")

print("=== Kalkulator Keuangan ===")

# Input data
pendapatan_harian = float(input("Masukkan pendapatan per hari (Rp): "))
hari_kerja = int(input("Masukkan jumlah hari kerja dalam seminggu: "))
pengeluaran_harian = float(input("Masukkan pengeluaran rata-rata per hari (Rp): "))

# Proses perhitungan
total_pendapatan = pendapatan_harian * hari_kerja
total_pengeluaran = pengeluaran_harian * hari_kerja
tabungan = total_pendapatan - total_pengeluaran

# Output utama
print("\n💵 Total pendapatan mingguan:", total_pendapatan, "rupiah")
print("💸 Total pengeluaran mingguan:", total_pengeluaran, "rupiah")
print("🏦 Total tabungan kamu minggu ini:", tabungan, "rupiah")

# Analisis sederhana dengan nested if-else
if tabungan > 1000000:
    print("\n💰 Hebat! Kamu mengelola uangmu dengan sangat baik.")
else:
    if tabungan > 0:
        print("\n📊 Kamu masih bisa menabung sedikit, tapi coba kurangi pengeluaran agar lebih efisien.")
    else:
        print("\n⚠️ Pengeluaran kamu melebihi pendapatan! Saatnya evaluasi gaya hidup dan anggaran.")

"""# **Tugas**

1.   Mengidentifikasi Predikat dari IPK Mahasiswa

Tulis program untuk mengidentifikasi predikat dari IPK Mahasiswa.
Rentang dan predikat :
IPK 2,00-2,75 Memuaskan.
IPK 2,76-3,50 Sangat memuaskan.
IPK 3,51-4,00 Dengan pujian (Cumlaude)

2.   Menentukan Bilangan Ganjil atau Genap

Buat program untuk memeriksa apakah bilangan yang dimasukkan adalah ganjil atau genap.

3.   Menentukan Kelulusan Siswa

Buat program yang menentukan apakah seorang siswa lulus berdasarkan nilai yang dimasukkan. Syarat kelulusan: nilai ≥ 60.

4.   Menentukan Diskon Berdasarkan Jumlah Belanja

Buat program untuk menentukan diskon berdasarkan jumlah belanja:
•	Jika belanja ≥ 1.000.000, diskon 10%.
•	Jika belanja < 1.000.000, tidak ada diskon.

5.   Menentukan Kategori Usia

Tulis program yang menentukan kategori usia berdasarkan input umur:
•	Anak-anak (0-12 tahun)
•	Remaja (13-17 tahun)
•	Dewasa (18 tahun ke atas)

6.   Menentukan Nilai Huruf

Buat program untuk mengonversi nilai angka menjadi nilai huruf:
•	A: nilai ≥ 85
•	B: 70 ≤ nilai < 85
•	C: 50 ≤ nilai < 70
•	D: nilai < 50

7.   Menentukan Tahun Kabisat

Tulis program untuk memeriksa apakah sebuah tahun adalah tahun kabisat atau bukan.

8.   Menentukan Angka Terbesar

Buat program untuk menemukan angka terbesar dari tiga angka yang dimasukkan pengguna.

9.   Menentukan Jenis Segitiga

Tulis program untuk menentukan jenis segitiga berdasarkan panjang tiga sisinya:
•	Sama Sisi: semua sisi sama panjang
•	Sama Kaki: dua sisi sama panjang
•	Sembarang: semua sisi berbeda panjang

10.  Sistem Penilaian Sederhana

Buat program untuk menentukan status siswa berdasarkan nilai ujian dan nilai tugas:
•	Lulus: nilai ujian ≥ 60 dan nilai tugas ≥ 70
•	Tidak Lulus: selain itu.

**Rumus** **Kabisat**

Jika tahun itu dibagi 4, maka itu adalah tahun kabisat, tetapi ada pengecualian...

Jika tahun itu juga dibagi 100, maka tahun itu TIDAK kabisat, kecuali...

Jika tahun itu dibagi 400, maka tahun itu tetap kabisat.
Jadi, untuk memudahkan:

Tahun yang bisa dibagi 4 adalah kabisat, kecuali kalau itu juga bisa dibagi 100, tetapi jika bisa dibagi 400, tetap kabisat.
Contoh:

Tahun 2020: Bisa dibagi 4, jadi kabisat.

Tahun 1900: Bisa dibagi 100, tapi tidak bisa dibagi 400, jadi bukan kabisat.

Tahun 2000: Bisa dibagi 400, jadi tahun kabisat.
"""